version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
# Good practise, because Windows line endings are different from Unix/Linux ones
- cmd: git config --global core.autocrlf true
install:
# Install repo specific stuff here
before_build:
# Display .NET Core version
- cmd: dotnet --version
# Display minimal restore text
- cmd: dotnet restore ./InfoSearcher/InfoSearcher.csporj --verbosity m
build_script:
# output will be in ./src/bin/debug/netcoreapp1.1/publish
- cmd: dotnet publish -c Release ./InfoSearcher/InfoSearcher.csporj
after_build:
# For once the build has completed
artifacts:
- path: '\Build\Release\netcoreapp2.0\publish'
  name: Console
clone_depth: 1
deploy: off
